<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net45</TargetFrameworks>
    <AssemblyName>pdftosvg</AssemblyName>
    <RootNamespace>PdfToSvg</RootNamespace>
    <ApplicationIcon>Resources\pdftosvg-cli.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\PdfToSvg\**\*.cs" Visible="false" />
    <Compile Remove="..\PdfToSvg\bin\Properties\AssemblyInfo.cs" Visible="false" />
    <Compile Remove="..\PdfToSvg\bin\**\*.cs" Visible="false" />
    <Compile Remove="..\PdfToSvg\obj\**\*.cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\pdftosvg-cli.ico" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PdfToSvg.Cli.Tests$(PdfToSvgPublicKeySuffix)"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net45" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfToSvg.SourceGenerators\PdfToSvg.SourceGenerators.csproj" SetTargetFramework="TargetFramework=netstandard2.0" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
