<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <VersionPrefix>1.9.0</VersionPrefix>
    <Product>PdfToSvg.NET</Product>
    <Authors>Daniel Mester Pirttijärvi</Authors>
    <Copyright>Copyright © Daniel Mester Pirttijärvi $([System.DateTime]::Now.Year)</Copyright>
  </PropertyGroup>

  <!-- Code -->
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <!-- Feature defines -->
  <PropertyGroup>
    <DefineConstants Condition="'$(TargetFramework)' != 'net40'">$(DefineConstants);HAVE_ASYNC</DefineConstants>
    <DefineConstants Condition="'$(TargetFramework)' == 'netstandard2.1' Or $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net5.0'))">$(DefineConstants);HAVE_NULLABLE;HAVE_ASYNC_ENUMERABLE</DefineConstants>
    <DefineConstants Condition="'$(TargetFramework)' != 'netstandard1.6'">$(DefineConstants);HAVE_STREAM_BEGINEND</DefineConstants>
  </PropertyGroup>

  <!-- Strong name signing -->
  <PropertyGroup Condition="$(Configuration) == 'Release' And $(PdfToSvgKeyFile) != ''">
    <SignAssembly>true</SignAssembly>
    <PdfToSvgPublicKey>002400000480000094000000060200000024000052534131000400000100010061da6a0cd2c597cfa715f18b3d8fd236eb8fa0f35e361777a94c832c9752612fe0350913a95cb36f633d853dfffb3cf662c48e110ab9b808158c27d72d5e2d6d9aa5b7016cb12e48faa278214e382f5936f04c79ca012ec32ef5194d9db01397d8a64a36441bb2ee8657fc62a9e4d92bd9fd134d5a2ebdc48c2c973a5788faa8</PdfToSvgPublicKey>
    <PdfToSvgPublicKeySuffix>, PublicKey=$(PdfToSvgPublicKey)</PdfToSvgPublicKeySuffix>
    <AssemblyOriginatorKeyFile>$(PdfToSvgKeyFile)</AssemblyOriginatorKeyFile>
    <DefineConstants>$(DefineConstants);SIGNED_ASSEMBLIES</DefineConstants>
  </PropertyGroup>

  <Target Name="WarnMissingPdfToSvgKeyFile" AfterTargets="Build">
    <Warning
      Text="Release build missing the PdfToSvgKeyFile property. The easiest way of configuring it is as an environment variable. The assemblies won't be signed."
      Condition="'$(Configuration)' == 'Release' And '$(PdfToSvgKeyFile)' == '' And '$(PdfToSvgSkipSigning)' == ''" />
  </Target>

  <!-- Embedded resources -->
  <ItemGroup Condition=" '$(TargetName)' != 'PdfToSvg.Packer' ">
    <EmbeddedResource Include="..\..\third-party\AdobeCMaps\PredefinedCMaps.bin" Visible="false">
      <LogicalName>PdfToSvg.CMaps.PredefinedCMaps.bin</LogicalName>
    </EmbeddedResource>

    <EmbeddedResource Include="..\..\third-party\AdobeGlyphList\glyphlist.txt" Visible="false">
      <LogicalName>PdfToSvg.Encodings.AdobeGlyphList.glyphlist.txt</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\AdobeGlyphList\zapfdingbats.txt" Visible="false">
      <LogicalName>PdfToSvg.Encodings.AdobeGlyphList.zapfdingbats.txt</LogicalName>
    </EmbeddedResource>

    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitDingbats.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitDingbats.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitFixed.modified.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitFixed.modified.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitFixedBold.modified.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitFixedBold.modified.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitFixedBoldItalic.modified.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitFixedBoldItalic.modified.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitFixedItalic.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitFixedItalic.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSans.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSans.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSansBold.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSansBold.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSansBoldItalic.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSansBoldItalic.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSansItalic.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSansItalic.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSerif.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSerif.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSerifBold.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSerifBold.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSerifBoldItalic.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSerifBoldItalic.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSerifItalic.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSerifItalic.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\FoxitSymbol.cff" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.FoxitSymbol.cff</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\third-party\StandardFonts\LICENSE" Visible="false">
      <LogicalName>PdfToSvg.Fonts.StandardFonts.LICENSE</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>