name: Build and test

on:
  push:
    branches: [ master, 'v*' ]
  pull_request:
    branches: [ master ]

env:
  PdfToSvgSkipSigning: true
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  SatelliteResourceLanguages: en  # See https://github.com/dotnet/sdk/issues/37636

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-22.04', 'windows-latest' ]

    steps:
    - uses: actions/checkout@v6

    - name: Get JPEG 2000 conformance test files
      if: vars.ITU_T803_CONFORMANCE_REPO != ''
      uses: actions/checkout@v6
      with:
        repository: ${{ vars.ITU_T803_CONFORMANCE_REPO }}
        token: ${{ secrets.ITU_T803_CONFORMANCE_TOKEN }}
        path: tests/TestFiles/T.803-JPEG2000-conformance

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          8.0.x
          10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test tests/PdfToSvg.Tests/PdfToSvg.Tests.csproj --no-build -c Release --verbosity normal --collect "Code Coverage;Format=cobertura" --results-directory TestResults

    - name: Test (scalar)
      run: dotnet test tests/PdfToSvg.Tests.Scalar/PdfToSvg.Tests.Scalar.csproj --no-build -c Release --verbosity normal --collect "Code Coverage;Format=cobertura" --results-directory TestResults

    - name: Test (Vector128)
      run: dotnet test tests/PdfToSvg.Tests.Vector128/PdfToSvg.Tests.Vector128.csproj --no-build -c Release --verbosity normal --collect "Code Coverage;Format=cobertura" --results-directory TestResults

    - name: Test CLI
      if: ${{ matrix.os == 'windows-latest' }}
      run: dotnet test tests/PdfToSvg.Cli.Tests/PdfToSvg.Cli.Tests.csproj --no-build -c Release --verbosity normal --results-directory TestResults

    - name: Test CLI Native AOT
      if: ${{ matrix.os == 'windows-latest' }}
      run: dotnet test tests/PdfToSvg.Cli.NativeAot.Tests/PdfToSvg.Cli.NativeAot.Tests.csproj --no-build -c Release --verbosity normal --results-directory TestResults

    - name: Code coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: "TestResults/**/*.cobertura.xml"
        targetdir: "TestReport"
        reporttypes: "Html"
        assemblyfilters: '+PdfToSvg'
        classfilters: '-System.*'

    - uses: actions/upload-artifact@v6
      with:
        name: coverage-${{ matrix.os }}
        path: TestReport

    - uses: actions/upload-artifact@v6
      if: ${{ failure() }}
      with:
        name: actual-${{ matrix.os }}
        path: tests/TestFiles/Own/actual-**
